### ISSUE TITLE
Upside-down barrels emptying contents only when powered

### ISSUE THREAD

**Issue by Typhonidite** [RecraftorsMC/Chests-are-Chests#1]
I believe it would be a better implementation of the idea if they only emptied their contents when powered by a redstone signal, rather than whenever opened.
Say I wanted a secret little barrel stache hidey-hole in my ceiling. This is to prevent all of my stored items from dropping out when I didn't intend for them to.

![2023-12-07_01 59 17](https://github.com/RecraftorsMC/Chests-are-Chests/assets/71224403/0459762d-cbf8-4d69-9ed7-b1e217b2a6b9)
![2023-12-07_01 59 29-edit](https://github.com/RecraftorsMC/Chests-are-Chests/assets/71224403/1421bdd0-2cbc-4920-a1ed-ccb04b8c2c98)
![2023-12-07_01 59 42-edit](https://github.com/RecraftorsMC/Chests-are-Chests/assets/71224403/3f25f481-b674-4a53-b0cc-f950bb97e00f)

**Comment by NerjalNosk** [comment]
This could easily be made into a gamerule, albeit not really going along with the gist of the functionality.
Although your example shown in your screenshots is rather unsettling, for even an open trapdoor should prevent the items from falling. May I know what versions (mod, modloader and game) you are playing on?

**Comment by Typhonidite** [comment]
Ah, really? Truth be told, the scene provided was only an imitation. I had only assumed the mod didn't have the feature suggested above as your (quite in-depth) description and video showcase hadn't touched on anything like it.
A trapdoor being enough to stop it is good to know, but the above would still be very much appreciated, should you decide to implement it.

**Comment by NerjalNosk** [comment]
Oh alright, at least it means it is not an issue with me publishing unstable code.
I'll look into potentially adding it in a next version, thank you for the suggestion.
